### ISSUE TITLE
Add More API Versions

### ISSUE THREAD

**Issue by BobbyTowers** [PocketMine-PHP7/ManyWorlds-PHP7#3]
Can you add more API(newer) versions?

**Comment by flaxues** [comment]
Why this made for PHP7...

**Comment by BobbyTowers** [comment]
I'm using Imagical Mine 0.14.0 #296. The Essentials plugin you have with php7 works fine.

**Comment by ondraczsk** [comment]
imagical mine is on api 1.14.0 update to this(1.14.0)

**Comment by ondraczsk** [comment]
from console:[17:45:21] system> This server is running ImagicalMine version 1.0dev "ImagicalMine" (API 1.14.0)
[17:45:21] system> ImagicalMine is distributed under the LGPL License
[17:45:22] error> Could not load plugin 'ManyWorlds': Incompatible API version

**Comment by flaxues** [comment]
I changed it but you need to compile the .phar yourself for now

**Comment by ondraczsk** [comment]
After the update works! Thank you :smile:

**Comment by ondraczsk** [comment]
# **CLOSED**
